databases:
  - name: scratchy-pg
    plan: free
    user: scratchy
    databaseName: scratchy_database
    ipAllowList: [] # only allow internal connections

services:
  - type: redis
    plan: free
    name: scratchy-redis
    ipAllowList: [] # only allow internal connections
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  - type: web
    name: scratchy-api
    plan: starter plus
    env: docker
    branch: main
    autoDeploy: true
    healthCheckPath: /api/ping
    rootDir: api
    buildFilter:
      paths:
        - api/**
    envVars:
      - fromGroup: scratchy-api
      - key: DATABASE_URL
        fromDatabase:
          name: scratchy-pg
          property: connectionString
      - key: QUEUE_HOST
        fromService:
          type: redis
          name: scratchy-redis
          property: host
      - key: QUEUE_PORT
        fromService:
          type: redis
          name: scratchy-redis
          property: port

  - type: web
    name: scratchy-web
    plan: free
    env: docker
    autoDeploy: true
    buildFilter:
      paths:
        - bin/render/build-web.sh
        - Dockerfile
        - web/**
    envVars:
      - key: NODE_VERSION
        value: "18.12.0"
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: "https://api.scratchy.onrender.com/api/"
      - key: VITE_APP
        value: scratchy.onrender.com
      - key: VITE_ENABLE_DEBUG
        value: 0

envVarGroups:
  - name: scratchy-api
    envVars:
      - key: NODE_VERSION
        value: "18.12.0"
      - key: NODE_ENV
        value: production
      - key: DEBUG_LEVEL
        value: debug

      - key: CORS_URLS
        value: "https://scratchy-web.onrender.com,https://scratchy-api.onrender.com"
      - key: APP_URL
        value: "https://scratchy.onrender.com"
      - key: API_URL
        value: "https://scratchy-api.onrender.com/api"

      - key: COOKIE_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

      - key: DATABASE_PROVIDER
        value: postgres

      - key: DEBUG_LEVEL
        sync: false

      - key: MAILER_FROM
        value: "noreply@scratchy-api.onrender.com"
      - key: MAILER_SMTP_URL
        sync: false

      - key: S3_FILE_UPLOADS_BUCKET
        value: scratchy-uploads
      - key: S3_FILE_UPLOADS_ACCESS_KEY
        sync: false
      - key: S3_FILE_UPLOADS_SECRET_KEY
        sync: false

      - key: OAUTH_FACEBOOK_ID
        sync: false
      - key: OAUTH_FACEBOOK_SECRET
        sync: false
      - key: OAUTH_GITHUB_ID
        sync: false
      - key: OAUTH_GITHUB_SECRET
        sync: false
      - key: OAUTH_GOOGLE_ID
        sync: false
      - key: OAUTH_GOOGLE_SECRET
        sync: false
