/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-08-22 18:20:49 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost:30532/scratchy -C -t forgot_password_tokens -t migration -t email_confirmation_tokens -t users -s public
 *
 */


export namespace ForgotPasswordTokensFields {
    export type token = string;
    export type userId = string;
    export type expiresAt = Date;

}

export interface ForgotPasswordTokens {
    token: ForgotPasswordTokensFields.token;
    userId: ForgotPasswordTokensFields.userId;
    expiresAt: ForgotPasswordTokensFields.expiresAt;

}

export namespace MigrationFields {
    export type name = string;
    export type hash = string;
    export type date = Date;

}

export interface Migration {
    name: MigrationFields.name;
    hash: MigrationFields.hash;
    date: MigrationFields.date;

}

export namespace EmailConfirmationTokensFields {
    export type token = string;
    export type userId = string;
    export type expiresAt = Date;

}

export interface EmailConfirmationTokens {
    token: EmailConfirmationTokensFields.token;
    userId: EmailConfirmationTokensFields.userId;
    expiresAt: EmailConfirmationTokensFields.expiresAt;

}

export namespace UsersFields {
    export type id = string;
    export type email = string;
    export type password = string | null;
    export type firstName = string | null;
    export type lastName = string | null;
    export type isEmailConfirmed = boolean;
    export type lastLoginIp = string | null;
    export type lastLoginAt = Date | null;
    export type createdIp = string | null;
    export type createdAt = Date;
    export type updatedAt = Date | null;

}

export interface Users {
    id: UsersFields.id;
    email: UsersFields.email;
    password: UsersFields.password;
    firstName: UsersFields.firstName;
    lastName: UsersFields.lastName;
    isEmailConfirmed: UsersFields.isEmailConfirmed;
    lastLoginIp: UsersFields.lastLoginIp;
    lastLoginAt: UsersFields.lastLoginAt;
    createdIp: UsersFields.createdIp;
    createdAt: UsersFields.createdAt;
    updatedAt: UsersFields.updatedAt;

}
